### ISSUE TITLE
Implement more compact application

### ISSUE THREAD

**Issue by estambakio-sc** [OpusCapita/oci-test#3]
Meta-Info | Value
-- | --
ExtProjectId | JCPROC-01.2
Original Estimation | 4h
Remaining Estimation | 4h

When current Grails-based OCI-test application is Dockerized and [installed](https://github.com/OpusCapita/eproc-line-deployment/issues/63) into Azure Kubernetes service, it appears to require ~1G memory per instance to work properly. When multiple installations of [eproc-line-deployment](https://github.com/OpusCapita/eproc-line-deployment/) run at the same time (`master` branch and branches with ongoing development for individual applications) memory consumption for OCI-test adds up and its cost rises. At the same time this application does nothing special - it just renders HTML forms whose fields are based on content of `.property` files. It also has a narrow, development-time-only purpose and wasting resources for this app seems undesireable.

Rewriting it using Nodejs will greatly reduce its installation costs. 

Common configuration options take into account from following config.json
```json
{
  "public_oci_test_url": "http://localhost:3000",
  "public_opc_url": "http://localhost:8080/opc"
}
```

Installation properties for installer
```properties
#install.properties
opuscapita.ecosystem.services = opc, oci-test

#nodejs.properties
nodejs.applications.list = oci-test
nodejs.oci-test.application.port = 3001
nodejs.oci-test.application.host = 127.0.0.1
nodejs.oci-test.public.url = http://127.0.0.1:3001
```

**NOTES** for installer the artefact available as `com.opuscapita.node:oci-test:1.0.0-SNAPSHOT.zip` in maven repository

Related ticket: https://support.jcatalog.com/browse/OPC-10955

**Comment by estambakio-sc** [comment]
Demo: https://demo.eproc.dev.opuscapita.com/eproc-line-deployment/eproc-review-tests/oci-test/

**Comment by estambakio-sc** [comment]
We also need to deploy new Nodejs application to Maven repository in order to make it installable via https://github.com/OpusCapita/jcatalog-installer

**Comment by ddivin-sc** [comment]
Please, check it with opc, oci-test and latest installer.

**Comment by nstoliar-sc** [comment]
1. OCI does not work in FF and IE browsers.
2. If URL of `oci-test` application has not '/' slash at the end string, 'The requested URL /form was not found on this server.' error appears.

**Comment by dshwedovsky-sc** [comment]
OCI-test app was installed via jc-installer as node js app.
OCI functions, Ariba login and Oracle Transparent Punchout are worked correctly.
Problems:
1. OCI-test is worked under FF 68, Edge 81 and Chrome 81, but not in IE 11 (HTML1524: Invalid HTML5 DOCTYPE. Consider using the interoperable form "<!DOCTYPE html>".)
2. In config.json "public_oci_test_url": "http://shwed.scand/oci-test", but app can be opened only via URL http://shwed.scand:3001

**Comment by nlogich-sc** [comment]
Fixed [bugs](https://github.com/OpusCapita/oci-test/issues/3#issuecomment-624519297).

1. Transform _form.js_ script  from ES6 to ES5
2. Added _public_oci_test_url_ to all refs.

**Comment by ddivin-sc** [comment]
Code reviewed.

**Comment by ddivin-sc** [comment]
For QA: please, check it problems.

**Comment by dshwedovsky-sc** [comment]
Oci-test-1.0.0-20210118.071352-5 application was installed via jc-installer as nodeJs app.
OCI functions, Ariba login and Oracle Transparent Punchout are worked correctly under FF, Edge, Chrome, IE11.

**Comment by ddivin-sc** [comment]
Merged all changes to master.
